### ISSUE TITLE
Problem: some users don't like dark color theme

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#3]
All components are updated with the Light version.
Navigation is updated with the Switcher.
I've left a few screens as a preview: [URL](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?node-id=1476%3A14187&t=G5GULlMrSGxVIJYJ-1) and [URL](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?node-id=1476%3A14429&t=G5GULlMrSGxVIJYJ-1).

**Comment by power-f-GOD** [comment]
Hi, guys! I'm claiming this problem (for now) to solve it.📝

Thank you.🙌🏼

PS. Kindly, be it assigned to me.🙇🏼

Cc: @zolotokrylin

**Comment by power-f-GOD** [comment]
Ok. Since, `WIP limit <= 1`, I hereby defer my claim of this problem until I am done solving [#353](https://github.com/holdex/holdex-venture-studio/issues/353)

Thank you.🙌🏼

**Comment by power-f-GOD** [comment]
Hi, guys! I'm re-claiming this problem to solve it.📝

@zolotokrylin , kindly assign it to me and update its status as needed.🙌🏼

**Comment by power-f-GOD** [comment]
Hi, @predrag-us , kindly, I left a comment: https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC?node-id=569:8286#469215153 . 🤲🏼

Cc: @zolotokrylin , @markholdex

**Comment by zolotokrylin** [comment]
@power-f-GOD that's for the suggestion, but for now, please proceed with the current design. Thanks

**Comment by power-f-GOD** [comment]
> @power-f-GOD that's for the suggestion, but for now, please proceed with the current design. Thanks

😅Yeah, sure. I, already, am.✅😎

**Comment by power-f-GOD** [comment]
Oh. The `tailwind.config` is...🥲 So, I have to unlearn the conventional `tailwind` and then re-learn it/this.💔

**Comment by power-f-GOD** [comment]
Context problem solved.✅ Will make a PR as soon as #353 gets merged, since I branched from it.✔️

Going off for a little while.🤲🏼 Should be available for feedback, but off code temporarily (until ~24-36hrs are over).😴

<img width="1440" alt="Screenshot 2023-06-13 at 4 33 55 AM" src="https://github.com/holdex/holdex-venture-studio/assets/28790485/a56dd2d5-eb66-41d1-9d9a-107499426bb6">

**Comment by zolotokrylin** [comment]
@power-f-GOD well done! 
P.S. Next time, please notify us in PR directly by [requesting PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review), not in the issue (unless you don't have relevant PR being open). It is more simple and keeps things in context.

**Comment by power-f-GOD** [comment]
Actually, I had tried doing that, but I didn't see the regular button(s) on the right, so I guess the restrictions also apply since I'm not a member...

<img width="657" alt="Screenshot 2023-06-14 at 6 50 22 PM" src="https://github.com/holdex/holdex-venture-studio/assets/28790485/5122ff63-b891-458e-9521-471223f18a36">
