### ISSUE TITLE
Problem: wrong place for environment variable

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#411]
Problem: wrong place for environment variable
Should be in `.env` file

_Originally posted by @zolotokrylin in https://github.com/holdex/holdex-venture-studio/pull/406#discussion_r1233845128_

**Comment by georgeciubotaru** [comment]
@zolotokrylin I understand your problem, but I think adding this variable in .env will complicate things. Every time you need to check the `prod` env you need to restart the server and so on, plus if you modify the `.env` file, on the next restart it will be overridden because we are pulling env vars from Vercel.

**Comment by zolotokrylin** [comment]
@georgeciubotaru I disagree here. We should not toggle variables inside the codebase to replicate the environment variable behavior. 
TODO:
- add var to Vercel with false
- update readme with relevant instruction
There is already open PR.
Can you please handle this issue so we can close this PR please?
