### ISSUE TITLE
Problem: WhatsApp preview is bad

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#412]
<img width="987" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/dfce69b0-5a5f-442f-89ec-6668d5e78648">

Should be like in TG
<img width="495" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/2047222f-a8de-486b-a607-58487da97ea0">

**Comment by zolotokrylin** [comment]
@predrag-us please double confirm how it should be and double-check and pass it further. Thankx

**Comment by MuhammadArslanKhan96** [comment]
![image](https://github.com/holdex/holdex-venture-studio/assets/98827339/fd964c06-68a7-4b26-a842-755d47a8ccd7)

That's what I'm getting and whatsapp always shows link previews like this because design of telegram and whatsapp are different below is the image of preview for github link

![image](https://github.com/holdex/holdex-venture-studio/assets/98827339/2f2ffc79-0727-4bea-89a0-dbc84ec4bdda)

Just checked it two times if there is any difference

**Comment by zolotokrylin** [comment]
Thanks, it was fixed.
