### ISSUE TITLE
Problem: table UX/UI is not optimal

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#477]
# Problem statement

It is not easy to consume content in [this table ](https://holdex.io/c/learn/crypto-and-web3-events)
<img width="1051" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/d367c270-8b05-4f12-acaf-2ae50f889c59">

**Comment by predrag-us** [comment]
@zolotokrylin 

The table isn't the best solution to present this information, since it's too dense.
The table isn't totally implemented by design, but even if it is, this amount of information would still be too much to handle.
Also, you can check how the table looks on mobile devices ⏤ it's hardly usable (screenshot). 

<img width="444" alt="CleanShot 2023-07-31 at 10 50 02@2x" src="https://github.com/holdex/holdex-venture-studio/assets/18451941/fc423042-7d01-42c4-b5bf-b36bfcf4d415">

I'll shortly create a problem pointing out the differences between the implementation and design. 
Still, I would strongly advise you to translate the tables to a different format since no solution can handle this amount of information.

Tables should be used only for lightweight information, and this one exceeds that amount by a lot. 

Thank you.

**Comment by predrag-us** [comment]
Problem: The table isn't implemented by the design
