### ISSUE TITLE
Actions expect form-encoded data (received application/octet-stream)

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#495]
View details in Rollbar: [https://app.rollbar.com/a/holdex/fix/item/Holdex/4484](https://app.rollbar.com/a/holdex/fix/item/Holdex/4484)

```
Actions expect form-encoded data (received application/octet-stream)
```

**Comment by andreisucman** [comment]
The provided url gives 404. Please suggest how to reproduce the issue.

**Comment by georgeciubotaru** [comment]
Hey @andreisucman Thank you for your interest.
This issue is not yet documented to be ready for the developer, but you can try to select one of following:
https://github.com/holdex/holdex-venture-studio/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22

P.S. Leave a log for the one you will choose.

Have a great day.

**Comment by andreisucman** [comment]
> Hey @andreisucman Thank you for your interest. This issue is not yet documented to be ready for the developer, but you can try to select one of following: https://github.com/holdex/holdex-venture-studio/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22
> 
> P.S. Leave a log for the one you will choose.
> 
> Have a great day.

I need 1-2 days to learn svelte and I'll pick my first task. Is that ok?

**Comment by georgeciubotaru** [comment]
@andreisucman Sure, take your time
